### ISSUE TITLE
Windows 10 System.IO.FileSystem Error

### ISSUE THREAD

**Issue by itbeyond** [sqli/sqli-cordova-disk-space-plugin#5]
Hello,

I have tried several things to get around this error but have no idea how to solve it and googling etc is not helping maybe you can. I have installed the plugin setup for Windows 10 build. The system builds it all great but everytime I run the getFreeDiskSpace function I get this:

```
WinRTError: The system cannot find the file specified.

System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at DiskSpaceLibrary.DiskSpace.sizeFolder(StorageFolder folder)
   at DiskSpaceLibrary.DiskSpace.<>c__DisplayClass5_0.<infoTask>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.Ex
console-via-logger.js (173,15)
   {
      [functions]: ,
      __proto__: { },
      asyncOpCausalityId: 461,
      asyncOpSource: { },
      asyncOpType: "Windows.Foundation.IAsyncOperation`1<String>",
      description: "The system cannot find the file specified.

System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at DiskSpaceLibrary.DiskSpace.sizeFolder(StorageFolder folder)
   at DiskSpaceLibrary.DiskSpace.<>c__DisplayClass5_0.<infoTask>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.Ex",
      message: "The system cannot find the file specified.

System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at DiskSpaceLibrary.DiskSpace.sizeFolder(StorageFolder folder)
   at DiskSpaceLibrary.DiskSpace.<>c__DisplayClass5_0.<infoTask>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.Ex",
      name: "WinRTError",
      number: -2147024894
   }
```
I have also forked the code, loaded it locally and recompiled under VS 2017 then loaded the recompiled code and still get the same error.

**Comment by gigaga** [comment]
Can you check that your project is an UAP project?

**Comment by itbeyond** [comment]
It is a UWP project in VS 2017 and I have compiled for AnyCPU. I note that it appears the latest UWP systems does not seem to allow us to  read the file system directly with System.IO but I am not finding much information on this at all. I am getting exactly the same error message when I am using the Windows 10 cordova-plugin-zip v3.1.1 (custom modified) system that has a winmd pre-compiled file.

What is a UAP project - I get the same message when I use your github version also?

**Comment by itbeyond** [comment]
See my new Pull Request for a fix to Windows 10 UWP. #6
